apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-testacademy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-testacademy
  template:
    metadata:
      labels:
        app: k8s-testacademy
    spec:
      containers:
      - name: k8s-testacademy
        image: barabanuser02/testacademy
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
